Fix 4th sample in Readme.md
I don't think `should` is included in `mocha`, but I guess you know that since [should.js](https://github.com/tj/should.js) is on your username. :P Anyway, running the sample gave me `Error: Cannot find module 'should'` which was annoying. Simply replacing the word "should" with "assert" fixed it so I thought that's better consistency.

The next error was cookie parser:
`Error: Most middleware (like cookieParser) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.`

Lastly, `app` was defined twice and the first one on global scope didn't seem needed so I removed that.

(again, using latest Express, 4.10.3)